FROM mcr.microsoft.com/devcontainers/typescript-node:0-18-bullseye

RUN su node -c "npm install -g @angular/cli@14.2.1"
RUN su node -c "npm install -g node-sass"
RUN su node -c "npm install -g sass-loader"
RUN su node -c "npm install -g raw-loader"
